version: "3.8"
  
services:
  nginx_service:
    container_name: "nginx"
    build:
      context: ./requirements/nginx
      args:
        INTRA_LOGIN: ${INTRA_LOGIN}
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress_service
    init: true
    networks:
      - inception
    restart: on-failure

  wordpress_service:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_PRE: ${DB_PRE}
        DOMAIN_NAME: ${DOMAIN_NAME}
        WP_TITLE: ${WP_TITLE}
        WP_USER: ${WP_USER}
        WP_PASS: ${WP_PASS}
        WP_EMAIL: ${WP_EMAIL}
        WP_OTHER_USER: ${WP_OTHER_USER}
        WP_OTHER_EMAIL: ${WP_OTHER_EMAIL}
        WP_OTHER_PASS: ${WP_OTHER_PASS}
    expose:
      - 9000
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb_service
    init: true
    networks:
      - inception
    restart: on-failure

  mariadb_service:
    build: 
      context: ./requirements/mariadb
      args: 
         DB_NAME: ${DB_NAME}
         DB_USER: ${DB_USER}
         DB_PASS: ${DB_PASS}
         DB_ROOT: ${DB_ROOT}
         DB_ROOT_PASS: ${DB_ROOT_PASS}
         DB_HOST: ${DB_HOST}
         DP_PRE: ${DP_PRE}
    container_name: mariadb
    command: sh -c "echo 'echo "127.0.0.1 jebucoy.42.fr" >> /etc/hosts'"
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
    
volumes:
  wp_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/jebucoy/inception_mount/wp
      o: bind
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      device: /home/jebucoy/inception_mount/db
      o: bind

networks:
  inception:
    driver: bridge