version: "3.8"
  
services:
  nginx:
    container_name: "nginx"
    hostname: nginx
    build:
      context: ./requirements/nginx
      args:
        INTRA_LOGIN: ${INTRA_LOGIN}
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress
      - mariadb
    init: true
    networks:
      - inception
    restart: on-failure

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_PRE: ${DB_PRE}
        DOMAIN_NAME: ${DOMAIN_NAME}
        WP_TITLE: ${WP_TITLE}
        WP_USER: ${WP_USER}
        WP_PASS: ${WP_PASS}
        WP_EMAIL: ${WP_EMAIL}
        WP_OTHER_USER: ${WP_OTHER_USER}
        WP_OTHER_EMAIL: ${WP_OTHER_EMAIL}
        WP_OTHER_PASS: ${WP_OTHER_PASS}
        DB_ROOT_PASS: ${DB_ROOT_PASS}

    expose:
      - 9000
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    init: true
    networks:
      - inception
    restart: on-failure

  mariadb:
    container_name: mariadb
    hostname: mariadb
    build: 
      context: ./requirements/mariadb
      args: 
         DB_NAME: ${DB_NAME}
         DB_USER: ${DB_USER}
         DB_PASS: ${DB_PASS}
         DB_ROOT: ${DB_ROOT}
         DB_ROOT_PASS: ${DB_ROOT_PASS}
         DB_HOST: ${DB_HOST}
         DB_PRE: ${DB_PRE}
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
    
volumes:
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      device: /home/jebucoy/data/wp
      o: bind
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      device: /home/jebucoy/data/db
      o: bind

networks:
  inception:
    driver: bridge